#!/bin/bash

if [[ -z "${SERVICE_NAME}" ]]; then
  exec /usr/local/bin/consul agent -server -ui -bootstrap -data-dir /var/lib/consul -config-dir /etc/consul -client "0.0.0.0"
else
  MIN_NODES_SIZE="${MIN_NODES_SIZE:-3}"
  echo "swarm mode enabled: peers are behind $(dig +short $SERVICE_NAME) ip"
  while [[ $number_of_nodes -lt ${MIN_NODES_SIZE} ]]; do
    SELF_IP=$(dig +short $(hostname))
    while [ "$SELF_IP" == "" ]; do
      sleep 1
      SELF_IP=$(dig +short $(hostname))
    done
    NODES=$(dig +short tasks.${SERVICE_NAME})
    number_of_nodes=$(( $(echo $NODES | grep -o '\s' | wc -l) + 1 )) >/dev/null
    echo "we found $number_of_nodes nodes"
    sleep 1
    NODE_LIST=""
    for node in $NODES; do
      NODE_LIST="$NODE_LIST -retry-join $node"
    done
  done
  if [ "$EMERGENCY_RECOVERY" == "true" ]; then
    echo "generating peers.json"
    export NODES
    render.py /etc/consul/peers.json.j2 > /var/lib/consul/raft/peers.json
    cat /var/lib/consul/raft/peers.json
  fi
  cmd="/usr/local/bin/consul agent -server -ui $NODE_LIST -bootstrap-expect ${MIN_NODES_SIZE} -data-dir /var/lib/consul -config-dir /etc/consul -advertise $SELF_IP -client 0.0.0.0"
  echo "running $cmd"
  exec $cmd
fi
