#!/bin/bash

if [[ -z "${SERVICE_NAME}" ]]; then
  exec /usr/local/bin/consul agent -server -ui -bootstrap -data-dir /var/lib/consul -config-dir /etc/consul
else
  MIN_NODES_SIZE="${MIN_NODES_SIZE:-3}"
  echo "swarm mode enabled: peers are behind $(dig +short $SERVICE_NAME) ip"
  while [[ $number_of_nodes -lt ${MIN_NODES_SIZE} ]]; do
    sleep 1
    SELF_IP=$(dig +short $(hostname))
    NODES=$(dig +short tasks.${SERVICE_NAME})
    number_of_nodes=$(( $(echo $NODES | grep -o '\s' | wc -l) + 1 )) >/dev/null
    echo "we found $number_of_nodes nodes"
  done
  exec /usr/local/bin/consul agent -server -retry-join $SERVICE_NAME -bootstrap-expect ${MIN_NODES_SIZE} -data-dir /var/lib/consul -config-dir /etc/consul -advertise $SELF_IP -client "0.0.0.0"
fi
